# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='token',
            field=models.UUIDField(verbose_name='Token'),
        ),
    ]
