# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollector', '0004_measurement_pressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementDayAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('weight_min', models.FloatField(verbose_name='Weight (min.)')),
                ('weight_avg', models.FloatField(verbose_name='Weight (avg.)')),
                ('weight_max', models.FloatField(verbose_name='Weight (max.)')),
                ('temperature_min', models.SmallIntegerField(verbose_name='Temperature (min.)')),
                ('temperature_avg', models.SmallIntegerField(verbose_name='Temperature (avg.)')),
                ('temperature_max', models.SmallIntegerField(verbose_name='Temperature (max.)')),
                ('humidity_min', models.SmallIntegerField(verbose_name='Humidity (min.)')),
                ('humidity_avg', models.SmallIntegerField(verbose_name='Humidity (avg.)')),
                ('humidity_max', models.SmallIntegerField(verbose_name='Humidity (max.)')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollector.Scale')),
            ],
        ),
    ]
