# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollector', '0005_measurementdayaggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdayaggregation',
            name='note',
            field=models.CharField(blank=True, max_length=20, verbose_name='Note'),
        ),
    ]
