# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollector', '0006_measurementdayaggregation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdayaggregation',
            name='apixiu_weather',
            field=models.TextField(blank=True, help_text='for future use', verbose_name='JSON from APIXIU'),
        ),
        migrations.AddField(
            model_name='measurementdayaggregation',
            name='rain',
            field=models.FloatField(default=0.0, verbose_name='rain sum'),
        ),
    ]
