# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollector', '0007_auto_20180211_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdayaggregation',
            name='icon',
            field=models.URLField(blank=True, verbose_name='weather icon'),
        ),
    ]
